apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: color
  name: color
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      serviceAccountName: color-detection
      securityContext:
        runAsGroup: 0
      containers:
      # Green
      # - image: ghcr.io/teojp3/jpt-color-detection:green
      # Red
      - image: ghcr.io/teojp3/jpt-color-detection:red
        name: color-detection
        env:
        # green
        # - name: COLOR_LOWER_LIMIT
        #   value: "45,66,133"
        # - name: COLOR_UPPER_LIMIT
        #   value: "72,154,215"
        # red
        - name: COLOR_LOWER_LIMIT
          value: "0,150,150"    # lower hue 0°, saturation high (rich red), brightness moderate to avoid noise
        - name: COLOR_UPPER_LIMIT
          value: "10,255,255"   # hue up to ~10° to cover warm reds fully

        # Dont change  
        # - name: CROP_COORDS
        #   value: "250,0,390,0,390,480,250,480"
        - name: DETECTION_ZONE_WIDTH
          value: "30"
        - name: MOVEMENT_HORIZONTAL
          value: "0"
        - name: TRACKER_MAX_DISTANCE
          value: "200"
        - name: CONTOUR_MERGE_THRESHOLD
          value: "20"
        - name: KERNEL_OPEN
          value: "10"
        - name: KERNEL_CLOSE
          value: "10"
        - name: DRAW_CENTER_LINE
          value: "0"
        - name: V4L_WHITE_BALANCE_AUTOMATIC
          value: "0"
        - name: V4L_GAIN
          value: "64"
        - name: V4L_POWER_LINE_FREQUENCY
          value: "0"
        - name: V4L_BACKLIGHT_COMPENSATION
          value: "0"
        - name: V4L_AUTO_EXPOSURE
          value: "1"
        - name: V4L_EXPOSURE_TIME_ABSOLUTE
          value: "40"
        - name: V4L_EXPOSURE_DYNAMIC_FRAMERATE
          value: "0"
        - name: V4L_FOCUS_ABSOLUTE
          value: "0"
        - name: V4L_FOCUS_AUTOMATIC_CONTINUOUS
          value: "0"
        - name: V4L_ZOOM_ABSOLUTE
          value: "100"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - mountPath: /dev/video0
          name: video
        securityContext:
          privileged: true
        resources: {}
      volumes:
      - name: video
        hostPath:
          path: /dev/video0
status: {}
